name: Build Web App

on:
  push:
    branches:
      - '**'

jobs:
  build:
    environment: CI # lets us use vars set in the "CI" environment of this repo on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        working-directory: apps/web
        run: pnpm install

      - name: Set environment variables
        run: echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ vars.CLERK_PUBLISHABLE_KEY }}" >> "$GITHUB_ENV"

      - name: Build with opennextjs-cloudflare
        working-directory: apps/web
        run: pnpm opennextjs-cloudflare build
